### PR TITLE
[Update] README.md

### PR DESCRIPTION
**Pull request by t510599**
難得有吉祥物，不加進來太可惜了。

### CODE REVIEW

**Comment by a91082900** [comment]
This can be marked as hacktoberfest-accepted, but we won't merge it.

**Comment by secminhr** [comment]
> This can be marked as hacktoberfest-accepted, but we won't merge it.

I think that if libraries section in README.md is updated, it would maybe worth a merge?

**Comment by t510599** [comment]
> > This can be marked as hacktoberfest-accepted, but we won't merge it.
> 
> I think that if libraries section in README.md is updated, it would maybe worth a merge?

Ok, I'll do that.

**Comment by t510599** [comment]
I have added more information in README, including game play and new libraries.
Please check, thanks.

**Comment by a91082900** [comment]
Because I can't fall asleep, I decided to merge the branch now.

**Pull request merged**
